#paths where datas are stored
dataset = "data/VDB_16S_dataset.txt"
metadata = "data/VDB_16S_metadata.txt"

#path where to build database
db = "db/metagenomics.sqlite"

#column which contain phylogenetic informations for each OTU
taxa_info = "ConsensusLineage"
taxa_colnames = [
    "reign",
    "phylum",
    "class",
    "order",
    "family",
    "genus",
    "specie"
]