name: vdb_poster_ravy_thomas
channels:
  - conda-forge
dependencies:
  - python=3.8
  - ipykernel
  - ipywidgets
  - jupyter
  - pandas
  - streamlit
  - toml
  - plotly
  - matplotlib
  - seaborn
  - scikit-learn